language: c
sudo: false
install:
  - wget https://github.com/tstack/lnav/releases/download/v0.8.0/lnav-0.8.0-linux-64bit.zip
  - unzip lnav-0.8.0-linux-64bit.zip
  - lnav-0.8.0/lnav -i xensource.json
script:
  - lnav-0.8.0/lnav -C
