language: c
dist: trusty
sudo: false
install:
  - wget https://github.com/tstack/lnav/releases/download/v0.8.0/lnav-0.8.0-linux-64bit.zip
  - unzip lnav-0.8.0-linux-64bit.zip
  - wget https://github.com/tstack/lnav/releases/download/v0.8.5/lnav-0.8.5-linux-64bit.zip
  - unzip lnav-0.8.5-linux-64bit.zip
  - lnav-0.8.0/lnav -i *.json
script:
  - env PATH="./lnav-0.8.0:$PATH" bash -uex test.sh
  - env PATH="./lnav-0.8.5:$PATH" bash -uex test.sh
